services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: pluralsight
      POSTGRES_PASSWORD: pluralsight
    ports:
      - '5432:5432'
  events:
    image: events-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8081:8081'
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"   # RabbitMQ default port
      - "15672:15672" # RabbitMQ Management Plugin port
  payments:
    image: payments-service:0.0.1-SNAPSHOT
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8082:8082'
  registration:
    image: registration-service:0.0.1-SNAPSHOT
    depends_on:
      - mongo
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - '8080:8080'
  update:
    image: update-service:0.0.1-SNAPSHOT
    depends_on:
      - rabbitmq
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    deploy:
      replicas: 3
