###
GET http://localhost:8081/organizers

<> 2024-11-30T144324.200.json

###
GET http://localhost:8081/events/501

<> 2024-11-30T151657.404.json
<> 2024-11-30T144434.200.json
<> 2024-11-30T144353.500.json

###
GET http://localhost:8081/products?
    eventId=501

<> 2024-11-30T144737.200.json

###
GET http://localhost:8081/products/801

<> 2024-11-30T144737.200.json

###
POST http://localhost:8080/registrations
Content-Type: application/json

{
  "productId": 801,
  "attendeeName": "Srishti"
}

<> 2024-12-02T090710.200.json
<> 2024-12-02T080554.200.json
<> 2024-12-02T080544.200.json
<> 2024-12-02T075726.200.json
<> 2024-12-02T075721.200.json
<> 2024-12-02T075437.200.json
<> 2024-12-02T075030.200.json
<> 2024-12-02T075023.200.json
<> 2024-12-02T075002.400.json
<> 2024-11-30T151031.200.json
<> 2024-11-30T150954.404.json

###
GET http://localhost:8080/registrations/fdceb9dc-4fc8-4872-aaad-30adcbb154ad


# Spring Actuator

###
GET http://localhost:8080/actuator


###
GET http://localhost:8080/actuator/health


###
GET http://localhost:8080/actuator/beans


###
GET http://localhost:8080/actuator/conditions


###
GET http://localhost:8080/actuator/mappings


###
GET http://localhost:8080/actuator/loggers/org.springframework.web


###
POST http://localhost:8080/actuator/loggers/org.springframework.web
Content-Type: application/json

{
  "configuredLevel": "DEBUG"
}


###
GET http://localhost:8080/actuator/metrics


###
GET http://localhost:8080/actuator/metrics/http.server.requests


###
GET http://localhost:8080/actuator/metrics/http.server.requests?tag=method:POST&tag=uri:/registrations